///////////////////////////////////////////////////////////
//  classe_adherent.cs
//  Implementation of the Class adherent
//  Generated by Enterprise Architect
//  Created on:      30-avr.-2026 09:41:48
//  Original author: Oz
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class adherent {

		private string adresse_Adherent;
		private int code_Postal;
		private string date_Naissance;
		private string email;
		private string nom_Adherent;
		private int num_Fixe;
		private int num_Mobile;
		private string prenom;
		public Package1.classe m_classe;

		public adherent(){

		}

		~adherent(){

		}

		public void ajouter(){

		}

		public void consulter(){

		}

		public void supprimer(){

		}

	}//end adherent

}//end namespace Package1