///////////////////////////////////////////////////////////
//  classe_communication.cs
//  Implementation of the Class messagerie
//  Generated by Enterprise Architect
//  Created on:      30-avr.-2026 09:31:52
//  Original author: Oz
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class messagerie {

		private string destinataire;
		private string expediteur;
		private string mail;
		private string mot_de_passe;
		private string objet;
		private string serveurSMTP;
		private string utilisateur;
		public Package1.Systbiblio m_Systbiblio;

		public messagerie(){

		}

		~messagerie(){

		}

		/// 
		/// <param name="message"></param>
		public void envoyer(string message){

		}

	}//end messagerie

}//end namespace Package1