///////////////////////////////////////////////////////////
//  classe_Systbiblio.cs
//  Implementation of the Class Systbiblio
//  Generated by Enterprise Architect
//  Created on:      30-avr.-2026 09:29:43
//  Original author: Utilisateur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class Systbiblio {

		public Package1.SGBD m_SGBD;
		public Package1.serveur_socket m_serveur_socket;

		public Systbiblio(){

		}

		~Systbiblio(){

		}

		/// 
		/// <param name="message"></param>
		public void getMessage(string message){

		}

		public void imprimer(){

		}

		public void Info_Adherant(){

		}

		public void Info_IHM_emprunter(){

		}

	}//end Systbiblio

}//end namespace Package1