///////////////////////////////////////////////////////////
//  classe_serveur_socket.cs
//  Implementation of the Class serveur_socket
//  Generated by Enterprise Architect
//  Created on:      30-avr.-2026 09:42:07
//  Original author: Oz
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Package1 {
	public class serveur_socket {

		private string IP;
		private string message;
		private int port;

		public serveur_socket(){

		}

		~serveur_socket(){

		}

		/// 
		/// <param name="IP"></param>
		/// <param name="port"></param>
		public void attendre(string IP, int port){

		}

		public void lire(){

		}

		/// 
		/// <param name="message"></param>
		public bool verification_signature(string message){

			return false;
		}

	}//end serveur_socket

}//end namespace Package1