///////////////////////////////////////////////////////////
//  classe_livre.cs
//  Implementation of the Class livre
//  Generated by Enterprise Architect
//  Created on:      30-avr.-2026 09:42:23
//  Original author: Oz
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class livre : article {

		private string auteur;
		private string ISBN;

		public livre(){

		}

		~livre(){

		}

	}//end livre

}//end namespace Package1