///////////////////////////////////////////////////////////
//  classe_classe.cs
//  Implementation of the Class classe
//  Generated by Enterprise Architect
//  Created on:      30-avr.-2026 09:41:52
//  Original author: Oz
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class classe {

		private string adresse_Etablissement;
		private string etablissement;
		private string niveau;
		private string nom_classe;
		private string professeur;
		public Package1.SGBD m_SGBD;

		public classe(){

		}

		~classe(){

		}

		public void ajouter(){

		}

		/// 
		/// <param name="classes"></param>
		public void consulter(string classes){

		}

		public void supprimer(){

		}

	}//end classe

}//end namespace Package1