///////////////////////////////////////////////////////////
//  classe_mineur.cs
//  Implementation of the Class mineur
//  Generated by Enterprise Architect
//  Created on:      30-avr.-2026 09:42:19
//  Original author: Oz
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class mineur : adherent {

		private *string responsable1;
		private *string responsable2;

		public mineur(){

		}

		~mineur(){

		}

	}//end mineur

}//end namespace Package1