///////////////////////////////////////////////////////////
//  classe_article.cs
//  Implementation of the Class article
//  Generated by Enterprise Architect
//  Created on:      30-avr.-2026 09:42:02
//  Original author: Oz
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Package1 {
	public class article {

		private string categorie;
		private string date;
		private float moyenne_Satisfaction;
		private string nom_article;
		private string tranche_Ages;

		public article(){

		}

		~article(){

		}

		public void ajouter(){

		}

		/// 
		/// <param name="article"></param>
		public void consulter(string article){

		}

		public void supprimer(){

		}

	}//end article

}//end namespace Package1