///////////////////////////////////////////////////////////
//  classe_admnistrateur.cs
//  Implementation of the Class admnistrateur
//  Generated by Enterprise Architect
//  Created on:      30-avr.-2026 09:42:16
//  Original author: Oz
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class admnistrateur : adherent {

		private string fonction;
		private string pseudo;

		public admnistrateur(){

		}

		~admnistrateur(){

		}

	}//end admnistrateur

}//end namespace Package1