///////////////////////////////////////////////////////////
//  jouet.cs
//  Implementation of the Class jouet
//  Generated by Enterprise Architect
//  Created on:      30-avr.-2026 09:42:28
//  Original author: Oz
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class jouet : article {

		private string marque;

		public jouet(){

		}

		~jouet(){

		}

	}//end jouet

}//end namespace Package1