///////////////////////////////////////////////////////////
//  SGBD.cs
//  Implementation of the Class SGBD
//  Generated by Enterprise Architect
//  Created on:      30-janv.-2026 09:20:45
//  Original author: Utilisateur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class SGBD {

		private string identifiant;
		private string mdp;
		public Package1.article m_article;
		public Package1.adherent m_adherent;

		public SGBD(){

		}

		~SGBD(){

		}

		public void connect(){

		}

		public void deconnect(){

		}

		public void ecrire(){

		}

		/// 
		/// <param name="mdp"></param>
		public string hachage(string mdp){

			return "";
		}

		public void lire(){

		}

		/// 
		/// <param name="requette_SQL"></param>
		public void prep_req_SQL(string requette_SQL){

		}

		/// 
		/// <param name="mdp"></param>
		public bool verification_hachage(string mdp){

			return false;
		}

	}//end SGBD

}//end namespace Package1